AllCops:
  Exclude:
    - 'bin/*'
    - 'config/initializers/backtrace_silencers.rb'
    - 'Rackfile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Style/Documentation:
  Enabled: false

Layout/EndOfLine:
  Enabled: false

Metrics/LineLength:
  Max: 110

Style/ClassVars:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Max: 60
